spring.application.name=payment-service

server.port=5006

spring.datasource.url=jdbc:mysql://localhost:3306/paymentdb_yt?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Rishaba@2428
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

razorpay.api.key="your razorpay api key"
rezorpay.api.secret="your razorpay api sceret"

stripe.api.key="your stripe api key"