services:
  eurekaserver:
    image: "rishaba2428/salon-eureka-yt:v1"
    container_name: eurekaserver
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - glowup

  gatewayserver:
    image: "rishaba2428/salon-gatewayserver-yt:v1"
    container_name: gatewayserver
    ports:
      - "5000:5000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
    depends_on:
      - eurekaserver
    networks:
      - glowup

  user-service:
    image: "rishaba2428/salon-user-yt:v1"
    container_name: userservice
    ports:
      - "5001:5001"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/userdb_yt
    depends_on:
      - eurekaserver
    networks:
      - glowup

  salon-service:
    image: "rishaba2428/salon-yt:v1"
    container_name: salonservice
    ports:
      - "5002:5002"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/salondb_yt
    depends_on:
      - eurekaserver
    networks:
      - glowup

  category-service:
    image: "rishaba2428/salon-category-yt:v1"
    container_name: categoryservice
    ports:
      - "5003:5003"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/categorydb_yt
    depends_on:
      - eurekaserver
    networks:
      - glowup

  service-offering:
    image: "rishaba2428/salon-service-offering-yt:v1"
    container_name: serviceoffering
    ports:
      - "5004:5004"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/servicesdb_yt
    depends_on:
      - eurekaserver
    networks:
      - glowup

  booking-service:
    image: "rishaba2428/salon-booking-yt:v1"
    container_name: bookingservice
    ports:
      - "5005:5005"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/bookingdb_yt
    depends_on:
      - eurekaserver
    networks:
      - glowup

  payment-service:
    image: "rishaba2428/salon-payment-yt:v1"
    container_name: paymentservice
    ports:
      - "5006:5006"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/paymentdb_yt
    depends_on:
      - eurekaserver
    networks:
      - glowup

networks:
  glowup:
    driver: "bridge"